CREATE TABLE [dbo].[CODE_RELATIONSHIP_TYPES]
(
[ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF_CODE_RELATIONSHIP_TYPE_ID] DEFAULT (newid()),
[Name] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DateAdded] [datetime] NOT NULL CONSTRAINT [DF_CODE_RELATIONSHIP_TYPE_DateAdded] DEFAULT (getdate()),
[DateModified] [datetime] NOT NULL CONSTRAINT [DF_CODE_RELATIONSHIP_TYPE_DateModified] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CODE_RELATIONSHIP_TYPES] ADD CONSTRAINT [PK_CODE_RELATIONSHIP_TYPE] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'VirtualFolder', N'Code', 'SCHEMA', N'dbo', 'TABLE', N'CODE_RELATIONSHIP_TYPES', NULL, NULL
GO
