CREATE TABLE [dbo].[CODE_RELATED_CODE]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[Main_Code_ID] [uniqueidentifier] NOT NULL,
[Related_Code_ID] [uniqueidentifier] NOT NULL,
[Relationship_Type_ID] [uniqueidentifier] NOT NULL,
[MetaData] [dbo].[JSON] NULL,
[DateAdded] [datetime] NOT NULL CONSTRAINT [DF_CODE_RELATED_CODE_DateAdded] DEFAULT (getdate()),
[DateModified] [datetime] NOT NULL CONSTRAINT [DF_CODE_RELATED_CODE_DateModified] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CODE_RELATED_CODE] ADD CONSTRAINT [PK_CODE_RELATED_CODE] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CODE_RELATED_CODE] ADD CONSTRAINT [FK_CODE_RELATED_CODE_Code] FOREIGN KEY ([Main_Code_ID]) REFERENCES [dbo].[Code] ([ID])
GO
ALTER TABLE [dbo].[CODE_RELATED_CODE] ADD CONSTRAINT [FK_CODE_RELATED_CODE_CODE_RELATIONSHIP_TYPES] FOREIGN KEY ([Relationship_Type_ID]) REFERENCES [dbo].[CODE_RELATIONSHIP_TYPES] ([ID])
GO
ALTER TABLE [dbo].[CODE_RELATED_CODE] ADD CONSTRAINT [FK_CODE_RELATED_CODE_Code1] FOREIGN KEY ([Related_Code_ID]) REFERENCES [dbo].[Code] ([ID])
GO
